---
# Debian-Specific Tasks for kraussnet.common

# Ensure Debian version is at least 9
- name: Asymworks Baseline (Debian) | Check Version
  when: ansible_distribution_version is version('9', '<')
  ansible.builtin.fail: msg='Unsupported Debian Version {{ ansible_distribution_version }} - Please Upgrade to Stretch or later'

# Install Basic Packages
- name: Asymworks Baseline (Debian) | Install Core Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - msmtp
      - msmtp-mta
      - nfs-common
      - ntp
      - python3-bcrypt
      - python3-passlib
      - python3-pip
      - ufw
      - vim
    update_cache: true

- name: Asymworks Baseline (Debian) | Install Restic Packages
  ansible.builtin.apt:
    name:
      - restic
      - sqlite3
    state: "{{ 'present' if restic_install else 'absent' }}"

# Set System Timezone
- name: Asymworks Baseline (Debian) | Set Timezone
  community.general.timezone:
    name: "{{ timezone }}"

# Setup NTP Server
- name: Asymworks Baseline (Debian) | Reset Network Time Servers
  ansible.builtin.lineinfile:
    path: /etc/ntp.conf
    search_string: 'pool.ntp.org'
    state: absent
  notify:
    - Asymworks Baseline (Debian) | Restart ntpd

- name: Asymworks Baseline (Debian) | Set Network Time Server
  ansible.builtin.lineinfile:
    path: /etc/ntp.conf
    regex: "^server "
    line: "server {{ ntp_server }}"
  notify:
    - Asymworks Baseline (Debian) | Restart ntpd

- name: Asymworks Baseline (Debian) | Start Network Time Service
  ansible.builtin.service:
    name: ntp
    enabled: true
    state: started

# Install Certificates
- name: Asymworks Baseline (Debian) | Create CA Certificate Directory
  ansible.builtin.file:
    path: /usr/local/share/ca-certificates/asymworks
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Asymworks Baseline (Debian) | Copy CA Certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_list:
    - usr/local/share/ca-certificates/asymworks/Asymworks_Root_CA.crt
    - usr/local/share/ca-certificates/asymworks/Asymworks_Network_CA.crt
  notify: Asymworks Baseline | Update CA Certificates

# Setup Restic
- name: Asymworks Baseline (Debian) | Setup Restic Directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    state: "{{ 'directory' if restic_install else 'absent' }}"
  loop:
    - /etc/restic
    - /etc/restic/exclude.d
    - /etc/restic/include.d
    - /etc/restic/pre-run.d

- name: Asymworks Baseline (Debian) | Install Restic Script
  when: restic_install
  ansible.builtin.template:
    src: "etc/periodic/{{ item }}.j2"
    dest: "/etc/cron.daily/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - 40-restic-default
    - 70-restic-prune-default

- name: Asymworks Baseline (Debian) | Remove Restic Script
  when: not restic_install
  ansible.builtin.file:
    src: "/etc/cron.daily/{{ item }}"
    state: 'absent'
  loop:
    - 40-restic-default
    - 70-restic-prune-default
