---
# Post-Play Tasks for Alpine Hosts
# --------------------------------
# 
# Update Alpine LBU (Post Task)
#
# For whatever reason, lbu ci returns '1' even if it succeeds (i.e. running
# lbu st immediately after shows nothing).  So we'll ignore the return code
# and just look for an empty result.
#
- name: Asymworks Baseline Post-Task (Alpine) | Update Alpine LBU  # noqa: no-changed-when
  ansible.builtin.command:
    cmd: lbu ci
  when: alpine_diskless
  become: true
  register: ret
  failed_when: ret.stderr != ''
