---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian9
    image: debian:9
    dockerfile: Dockerfile.j2
    pre_build_image: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /lib/systemd/systemd

  - name: debian10
    image: debian:10
    dockerfile: Dockerfile.j2
    pre_build_image: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /lib/systemd/systemd

  - name: alpine313
    image: alpine:3.13
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /sbin/init

  - name: alpine314
    image: alpine:3.14
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /sbin/init

  - name: alpine315
    image: alpine:3.15
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /sbin/init

  - name: ubuntu20.04
    image: ubuntu:20.04
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /sbin/init

  - name: ubuntu21.10
    image: ubuntu:21.10
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    security_opts:
      - seccomp=unconfined
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
