---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
    command: "/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
